repos:
  - repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
    - id: black
      args: ["--line-length=120"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    - id: flake8
      args: ["--config=./backend/.flake8", "./backend"]

  -   repo: https://github.com/timothycrosley/isort
      rev: 5.7.0
      hooks:
      - id: isort
        args: ["--line-length=120", "--profile=black"]
