repos:
  - repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
    - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    - id: flake8

  -   repo: https://github.com/timothycrosley/isort
      rev: 5.7.0
      hooks:
      - id: isort

  -   repo: https://github.com/fsouza/autoflake8
      rev: v0.2.2
      hooks:
      - id: autoflake8
        args: ["--remove-unused-variables", "--recursive", "--exclude=__init__.py"]
