repos:
  - repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
    - id: black
      args: ["--line-length=120", "./backend"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    - id: flake8
      args: ["max-line-length = 120", "exclude = __init__.py"]

  -   repo: https://github.com/timothycrosley/isort
      rev: 5.7.0
      hooks:
      - id: isort
        args: ["--line-length=120", "--profile=black"]

  -   repo: https://github.com/fsouza/autoflake8
      rev: v0.2.2
      hooks:
      - id: autoflake8
        args: ["--remove-unused-variables", "--recursive", "--exclude=__init__.py"]
