repos:
-   repo: local
    rev: meta
    hooks:
    -   id: black
        language: python
        name: Run black
        description: Check code format
        entry: poetry run black --check src tests
        always_run: true
        stages:
          - commit
#TODO: Fixar, incluir o Flake8 e testes
