version: '3'

services:

# Databases

  postgres:
    image: postgres
    container_name: postgres

    environment:
      POSTGRES_PASSWORD: secret
      TZ: 'GMT-3'
      PGTZ: 'GMT-3'

    ports:
      - 5432:5432

    volumes:
      - .data/db:/var/lib/postgresql/data

    networks:
      - store-network

# Cache

  redis:
    image: redis
    container_name: redis

    ports:
      - 6379:6379

    networks:
      - store-network

    volumes:
      - .data/cache:/data

# AWS Services

  aws-localstack:
    container_name: aws-localstack
    image: localstack/localstack

    ports:
      - 4566-4572:4566-4572

    environment:
      - EDGE_PORT=4566
      - SERVICES=sqs,s3
      - DATA_DIR=/tmp/localstack/data

    networks:
      - store-network

    volumes:
      - .data/localstack:/tmp/localstack

# Monitoring

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch

    ulimits:
      memlock:
        soft: -1
        hard: -1

    volumes:
      - .data/elasticsearch:/usr/share/elasticsearch/data

    ports:
      - 9200:9200

    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"

    networks:
      - store-network

    healthcheck:
      interval: 20s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    container_name: kibana

    ports:
      - 5601:5601

    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

    depends_on:
      elasticsearch:
        condition: service_healthy

    networks:
      - store-network

    healthcheck:
      interval: 10s
      retries: 20
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5601/api/status

  apm-server:
    container_name: apm-server
    image: docker.elastic.co/apm/apm-server:7.14.0

    depends_on:
      elasticsearch:
        condition: service_healthy

      kibana:
        condition: service_healthy

    cap_add: ["CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID"]
    cap_drop: ["ALL"]

    ports:
      - 8200:8200

    networks:
      - store-network

    environment:
      - apm-server.rum.enabled=true
      - setup.kibana.host=kibana:5601
      - setup.template.settings.index.number_of_replicas=0
      - apm-server.kibana.enabled=true
      - apm-server.kibana.host=kibana:5601
      - output.elasticsearch.hosts=["elasticsearch:9200"]

    healthcheck:
      interval: 10s
      retries: 20
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5601/api/status


networks:
  store-network:
    driver: bridge
