version: '3'

services:

# Databases

  postgres:
    image: postgres
    container_name: postgres

    environment:
      POSTGRES_PASSWORD: secret
      TZ: 'GMT-3'
      PGTZ: 'GMT-3'

    ports:
      - 5432:5432

    volumes:
      - .data/db:/var/lib/postgresql/data

    networks:
      - store-network

# Cache

  redis:
    image: redis
    container_name: redis

    ports:
      - 6379:6379

    networks:
      - store-network

    volumes:
      - .data/cache:/data

# AWS Services

  aws-localstack:
    container_name: aws-localstack
    image: localstack/localstack

    ports:
      - 4566-4572:4566-4572

    environment:
      - EDGE_PORT=4566
      - SERVICES=sqs,s3
      - DATA_DIR=/tmp/localstack/data

    networks:
      - store-network

    volumes:
      - .data/localstack:/tmp/localstack

networks:
  store-network:
    driver: bridge
