"""empty message

Revision ID: 0567010550ba
Revises: c017c35ebee6
Create Date: 2021-09-18 17:44:34.053289

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0567010550ba"
down_revision = "c017c35ebee6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    order_enum = postgresql.ENUM("PENDING", "COMPLETED", "CANCELED", name="orderenum")
    order_enum.create(op.get_bind())
    op.add_column(
        "orders",
        sa.Column("status", postgresql.ENUM("PENDING", "COMPLETED", "CANCELED", name="orderenum"), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "status")
    order_enum = postgresql.ENUM("PENDING", "COMPLETED", "CANCELED", name="orderenum")
    order_enum.create(op.get_bind())
    # ### end Alembic commands ###
