"""empty message

Revision ID: 3bd236c2b554
Revises: 0567010550ba
Create Date: 2021-09-26 19:35:33.189162

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3bd236c2b554"
down_revision = "0567010550ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("clients", "email", existing_type=sa.VARCHAR(length=100), nullable=False)
    op.alter_column("clients", "phone", existing_type=sa.BIGINT(), nullable=False)
    op.create_index(op.f("ix_clients_created_at"), "clients", ["created_at"], unique=False)
    op.create_index(op.f("ix_clients_email"), "clients", ["email"], unique=False)
    op.create_index(op.f("ix_clients_id"), "clients", ["id"], unique=False)
    op.create_index(op.f("ix_clients_name"), "clients", ["name"], unique=False)
    op.create_index(op.f("ix_clients_phone"), "clients", ["phone"], unique=False)
    op.drop_constraint("files_bucket_key_key", "files", type_="unique")
    op.drop_constraint("files_hash_key", "files", type_="unique")
    op.create_index(op.f("ix_files_bucket_key"), "files", ["bucket_key"], unique=False)
    op.create_index(op.f("ix_files_hash"), "files", ["hash"], unique=False)
    op.create_index(op.f("ix_files_uploaded_at"), "files", ["uploaded_at"], unique=False)
    op.alter_column("fiscal_notes", "description", existing_type=sa.VARCHAR(), nullable=False)
    op.create_index(op.f("ix_fiscal_notes_description"), "fiscal_notes", ["description"], unique=False)
    op.create_index(op.f("ix_fiscal_notes_file_id"), "fiscal_notes", ["file_id"], unique=False)
    op.create_index(op.f("ix_fiscal_notes_id"), "fiscal_notes", ["id"], unique=False)
    op.create_index(op.f("ix_fiscal_notes_purchase_date"), "fiscal_notes", ["purchase_date"], unique=False)
    op.alter_column("items", "avaliable", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("items", "file_id", existing_type=sa.VARCHAR(), nullable=False)
    op.create_index(op.f("ix_items_avaliable"), "items", ["avaliable"], unique=False)
    op.create_index(op.f("ix_items_buy_value"), "items", ["buy_value"], unique=False)
    op.create_index(op.f("ix_items_code"), "items", ["code"], unique=False)
    op.create_index(op.f("ix_items_file_id"), "items", ["file_id"], unique=False)
    op.create_index(op.f("ix_items_fiscal_note_id"), "items", ["fiscal_note_id"], unique=False)
    op.create_index(op.f("ix_items_id"), "items", ["id"], unique=False)
    op.create_index(op.f("ix_items_name"), "items", ["name"], unique=False)
    op.create_index(op.f("ix_items_sugested_sell_value"), "items", ["sugested_sell_value"], unique=False)
    op.drop_constraint("items_fiscal_note_id_fkey", "items", type_="foreignkey")
    op.create_foreign_key(None, "items", "fiscal_notes", ["fiscal_note_id"], ["id"])
    op.alter_column("order_details", "order_id", existing_type=sa.INTEGER(), nullable=True)
    op.create_index(op.f("ix_order_details_buy_value"), "order_details", ["buy_value"], unique=False)
    op.create_index(op.f("ix_order_details_id"), "order_details", ["id"], unique=False)
    op.create_index(op.f("ix_order_details_item_id"), "order_details", ["item_id"], unique=False)
    op.create_index(op.f("ix_order_details_order_id"), "order_details", ["order_id"], unique=False)
    op.create_index(op.f("ix_order_details_sell_value"), "order_details", ["sell_value"], unique=False)
    op.drop_constraint("order_details_item_id_fkey", "order_details", type_="foreignkey")
    op.drop_constraint("order_details_order_id_fkey", "order_details", type_="foreignkey")
    op.create_foreign_key(None, "order_details", "orders", ["order_id"], ["id"])
    op.create_foreign_key(None, "order_details", "items", ["item_id"], ["id"])
    op.alter_column("orders", "date", existing_type=postgresql.TIMESTAMP(), nullable=False)
    op.alter_column(
        "orders",
        "status",
        existing_type=postgresql.ENUM("PENDING", "COMPLETED", "CANCELED", name="orderenum"),
        nullable=False,
    )
    op.create_index(op.f("ix_orders_client_id"), "orders", ["client_id"], unique=False)
    op.create_index(op.f("ix_orders_date"), "orders", ["date"], unique=False)
    op.create_index(op.f("ix_orders_id"), "orders", ["id"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.drop_constraint("orders_client_id_fkey", "orders", type_="foreignkey")
    op.create_foreign_key(None, "orders", "clients", ["client_id"], ["id"])
    op.drop_constraint("users_email_key", "users", type_="unique")
    op.create_index(op.f("ix_users_admin"), "users", ["admin"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(op.f("ix_users_name"), "users", ["name"], unique=False)
    op.create_index(op.f("ix_users_password_hash"), "users", ["password_hash"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_password_hash"), table_name="users")
    op.drop_index(op.f("ix_users_name"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_admin"), table_name="users")
    op.create_unique_constraint("users_email_key", "users", ["email"])
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.create_foreign_key("orders_client_id_fkey", "orders", "clients", ["client_id"], ["id"], ondelete="CASCADE")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_date"), table_name="orders")
    op.drop_index(op.f("ix_orders_client_id"), table_name="orders")
    op.alter_column(
        "orders",
        "status",
        existing_type=postgresql.ENUM("PENDING", "COMPLETED", "CANCELED", name="orderenum"),
        nullable=True,
    )
    op.alter_column("orders", "date", existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.drop_constraint(None, "order_details", type_="foreignkey")
    op.drop_constraint(None, "order_details", type_="foreignkey")
    op.create_foreign_key(
        "order_details_order_id_fkey", "order_details", "orders", ["order_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        "order_details_item_id_fkey", "order_details", "items", ["item_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_index(op.f("ix_order_details_sell_value"), table_name="order_details")
    op.drop_index(op.f("ix_order_details_order_id"), table_name="order_details")
    op.drop_index(op.f("ix_order_details_item_id"), table_name="order_details")
    op.drop_index(op.f("ix_order_details_id"), table_name="order_details")
    op.drop_index(op.f("ix_order_details_buy_value"), table_name="order_details")
    op.alter_column("order_details", "order_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_constraint(None, "items", type_="foreignkey")
    op.create_foreign_key(
        "items_fiscal_note_id_fkey", "items", "fiscal_notes", ["fiscal_note_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_index(op.f("ix_items_sugested_sell_value"), table_name="items")
    op.drop_index(op.f("ix_items_name"), table_name="items")
    op.drop_index(op.f("ix_items_id"), table_name="items")
    op.drop_index(op.f("ix_items_fiscal_note_id"), table_name="items")
    op.drop_index(op.f("ix_items_file_id"), table_name="items")
    op.drop_index(op.f("ix_items_code"), table_name="items")
    op.drop_index(op.f("ix_items_buy_value"), table_name="items")
    op.drop_index(op.f("ix_items_avaliable"), table_name="items")
    op.alter_column("items", "file_id", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("items", "avaliable", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_index(op.f("ix_fiscal_notes_purchase_date"), table_name="fiscal_notes")
    op.drop_index(op.f("ix_fiscal_notes_id"), table_name="fiscal_notes")
    op.drop_index(op.f("ix_fiscal_notes_file_id"), table_name="fiscal_notes")
    op.drop_index(op.f("ix_fiscal_notes_description"), table_name="fiscal_notes")
    op.alter_column("fiscal_notes", "description", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_index(op.f("ix_files_uploaded_at"), table_name="files")
    op.drop_index(op.f("ix_files_hash"), table_name="files")
    op.drop_index(op.f("ix_files_bucket_key"), table_name="files")
    op.create_unique_constraint("files_hash_key", "files", ["hash"])
    op.create_unique_constraint("files_bucket_key_key", "files", ["bucket_key"])
    op.drop_index(op.f("ix_clients_phone"), table_name="clients")
    op.drop_index(op.f("ix_clients_name"), table_name="clients")
    op.drop_index(op.f("ix_clients_id"), table_name="clients")
    op.drop_index(op.f("ix_clients_email"), table_name="clients")
    op.drop_index(op.f("ix_clients_created_at"), table_name="clients")
    op.alter_column("clients", "phone", existing_type=sa.BIGINT(), nullable=True)
    op.alter_column("clients", "email", existing_type=sa.VARCHAR(length=100), nullable=True)
    # ### end Alembic commands ###
