"""empty message

Revision ID: 7ab9eea782b2
Revises: 4fa9dc1e5822
Create Date: 2021-08-27 21:35:00.491220

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "7ab9eea782b2"
down_revision = "4fa9dc1e5822"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "files", ["bucket_key"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "files", type_="unique")
    # ### end Alembic commands ###
