"""empty message

Revision ID: bc7ad6de76b8
Revises: 78cb334a0fd6
Create Date: 2021-10-02 17:32:55.862217

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "bc7ad6de76b8"
down_revision = "78cb334a0fd6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f("ix_orders_description"), "orders", ["description"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orders_description"), table_name="orders")
    op.drop_column("orders", "description")
    # ### end Alembic commands ###
