"""Implementing balance and fiscal_note_items tables

Revision ID: 6099ed2a58e0
Revises: 78cb334a0fd6
Create Date: 2021-10-11 14:52:44.126077

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6099ed2a58e0"
down_revision = "78cb334a0fd6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "balance",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("type", sa.Enum("DEBT", "CREDIT", name="balancetype"), nullable=False),
        sa.Column(
            "operation",
            sa.Enum(
                "PAYMENT_OF_EMPLOYEES",
                "PAYMENT_OF_SUPPLIERS",
                "ANOTHER_PAYMENTS",
                "SALE_IN_PIX",
                "SALE_IN_DEBT",
                "SALE_IN_CREDIT",
                "SALE_IN_MONEY",
                name="operationtype",
            ),
            nullable=False,
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("owner_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_balance_created_at"), "balance", ["created_at"], unique=False)
    op.create_index(op.f("ix_balance_operation"), "balance", ["operation"], unique=False)
    op.create_index(op.f("ix_balance_owner_id"), "balance", ["owner_id"], unique=False)
    op.create_index(op.f("ix_balance_type"), "balance", ["type"], unique=False)
    op.create_table(
        "fiscal_note_items",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("buy_value", sa.Float(), nullable=False),
        sa.Column("sugested_sell_value", sa.Float(), nullable=False),
        sa.Column("owner_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("fiscal_note_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("item_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("file_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.bucket_key"],
        ),
        sa.ForeignKeyConstraint(
            ["fiscal_note_id"],
            ["fiscal_notes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fiscal_note_items_fiscal_note_id"), "fiscal_note_items", ["fiscal_note_id"], unique=False)
    op.create_index(op.f("ix_fiscal_note_items_item_id"), "fiscal_note_items", ["item_id"], unique=False)
    op.create_index(op.f("ix_fiscal_note_items_owner_id"), "fiscal_note_items", ["owner_id"], unique=False)
    op.create_index(
        op.f("ix_fiscal_note_items_sugested_sell_value"), "fiscal_note_items", ["sugested_sell_value"], unique=False
    )
    op.create_index(op.f("ix_clients_owner_id"), "clients", ["owner_id"], unique=False)
    op.create_index(op.f("ix_fiscal_notes_owner_id"), "fiscal_notes", ["owner_id"], unique=False)
    op.alter_column("items", "cost", existing_type=postgresql.DOUBLE_PRECISION(precision=53), nullable=True)
    op.create_index(op.f("ix_items_amount"), "items", ["amount"], unique=False)
    op.alter_column("order_details", "order_id", existing_type=postgresql.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_password_hash"), table_name="users")
    op.drop_index(op.f("ix_users_name"), table_name="users")
    op.drop_index(op.f("ix_orders_description"), table_name="orders")
    op.drop_index(op.f("ix_order_details_sell_value"), table_name="order_details")
    op.drop_index(op.f("ix_order_details_item_name"), table_name="order_details")
    op.drop_index(op.f("ix_order_details_cost"), table_name="order_details")
    op.alter_column("order_details", "order_id", existing_type=postgresql.UUID(), nullable=False)
    op.drop_index(op.f("ix_items_value"), table_name="items")
    op.drop_index(op.f("ix_items_cost"), table_name="items")
    op.drop_index(op.f("ix_items_amount"), table_name="items")
    op.alter_column("items", "cost", existing_type=postgresql.DOUBLE_PRECISION(precision=53), nullable=False)
    op.drop_index(op.f("ix_fiscal_notes_owner_id"), table_name="fiscal_notes")
    op.drop_index(op.f("ix_fiscal_notes_file_id"), table_name="fiscal_notes")
    op.drop_index(op.f("ix_fiscal_notes_description"), table_name="fiscal_notes")
    op.drop_index(op.f("ix_files_uploaded_at"), table_name="files")
    op.drop_index(op.f("ix_clients_phone"), table_name="clients")
    op.drop_index(op.f("ix_clients_owner_id"), table_name="clients")
    op.drop_index(op.f("ix_clients_created_at"), table_name="clients")
    op.drop_index(op.f("ix_fiscal_note_items_sugested_sell_value"), table_name="fiscal_note_items")
    op.drop_index(op.f("ix_fiscal_note_items_owner_id"), table_name="fiscal_note_items")
    op.drop_index(op.f("ix_fiscal_note_items_item_id"), table_name="fiscal_note_items")
    op.drop_index(op.f("ix_fiscal_note_items_fiscal_note_id"), table_name="fiscal_note_items")
    op.drop_index(op.f("ix_fiscal_note_items_file_id"), table_name="fiscal_note_items")
    op.drop_index(op.f("ix_fiscal_note_items_buy_value"), table_name="fiscal_note_items")
    op.drop_table("fiscal_note_items")
    op.drop_index(op.f("ix_balance_value"), table_name="balance")
    op.drop_index(op.f("ix_balance_type"), table_name="balance")
    op.drop_index(op.f("ix_balance_owner_id"), table_name="balance")
    op.drop_index(op.f("ix_balance_operation"), table_name="balance")
    op.drop_index(op.f("ix_balance_description"), table_name="balance")
    op.drop_index(op.f("ix_balance_created_at"), table_name="balance")
    op.drop_table("balance")
    # ### end Alembic commands ###
