"""empty message

Revision ID: 60f151e462e9
Revises: 6099ed2a58e0
Create Date: 2021-11-17 16:24:31.001099

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "60f151e462e9"
down_revision = "6099ed2a58e0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("clients", "email", nullable=True)
    op.alter_column("clients", "phone", nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("clients", "email", nullable=False)
    op.alter_column("clients", "phone", nullable=False)
    # ### end Alembic commands ###
