"""empty message

Revision ID: 9cb87c483a00
Revises: Reset migrations
Create Date: 2022-05-09 16:31:55.477593

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "9cb87c483a00"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files",
        sa.Column("bucket_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("bucket_key"),
    )
    op.create_index(op.f("ix_files_bucket_key"), "files", ["bucket_key"], unique=False)
    op.create_index(op.f("ix_files_hash"), "files", ["hash"], unique=False)
    op.create_table(
        "users",
        sa.Column("access_level", sa.Enum("ANONIMOUS", "USER", "SUPER_USER", name="accesslevel"), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_active"), "users", ["active"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "balance",
        sa.Column(
            "operation",
            sa.Enum(
                "SALE_IN_PIX",
                "SALE_IN_DEBT",
                "SALE_IN_CREDIT",
                "SALE_IN_MONEY",
                "SALE_IN_TRANSFER",
                "SALE_IN_BILLET",
                "SALE_OTHERS",
                "PAYMENT_OF_EMPLOYEES",
                "PAYMENT_OF_SUPPLIERS",
                "ANOTHER_PAYMENTS",
                name="operationtype",
            ),
            nullable=False,
        ),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("owner_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_balance_created_at"), "balance", ["created_at"], unique=False)
    op.create_index(op.f("ix_balance_owner_id"), "balance", ["owner_id"], unique=False)
    op.create_table(
        "clients",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("zip_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("owner_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_clients_email"), "clients", ["email"], unique=False)
    op.create_index(op.f("ix_clients_owner_id"), "clients", ["owner_id"], unique=False)
    op.create_table(
        "items",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=True),
        sa.Column("owner_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_items_code"), "items", ["code"], unique=False)
    op.create_index(op.f("ix_items_owner_id"), "items", ["owner_id"], unique=False)
    op.create_table(
        "orders",
        sa.Column("status", sa.Enum("PENDING", "COMPLETED", "CANCELED", name="orderstatus"), nullable=False),
        sa.Column(
            "sale_type",
            sa.Enum(
                "SALE_IN_PIX",
                "SALE_IN_DEBT",
                "SALE_IN_CREDIT",
                "SALE_IN_MONEY",
                "SALE_IN_TRANSFER",
                "SALE_IN_BILLET",
                "SALE_OTHERS",
                name="saletype",
            ),
            nullable=False,
        ),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("client_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("owner_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_client_id"), "orders", ["client_id"], unique=False)
    op.create_index(op.f("ix_orders_date"), "orders", ["date"], unique=False)
    op.create_index(op.f("ix_orders_owner_id"), "orders", ["owner_id"], unique=False)
    op.create_table(
        "order_details",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("item_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("item_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("item_amount", sa.Integer(), nullable=False),
        sa.Column("order_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_order_details_item_id"), "order_details", ["item_id"], unique=False)
    op.create_index(op.f("ix_order_details_order_id"), "order_details", ["order_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_details_order_id"), table_name="order_details")
    op.drop_index(op.f("ix_order_details_item_id"), table_name="order_details")
    op.drop_table("order_details")
    op.drop_index(op.f("ix_orders_owner_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_date"), table_name="orders")
    op.drop_index(op.f("ix_orders_client_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_items_owner_id"), table_name="items")
    op.drop_index(op.f("ix_items_code"), table_name="items")
    op.drop_table("items")
    op.drop_index(op.f("ix_clients_owner_id"), table_name="clients")
    op.drop_index(op.f("ix_clients_email"), table_name="clients")
    op.drop_table("clients")
    op.drop_index(op.f("ix_balance_owner_id"), table_name="balance")
    op.drop_index(op.f("ix_balance_created_at"), table_name="balance")
    op.drop_table("balance")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_active"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_files_hash"), table_name="files")
    op.drop_index(op.f("ix_files_bucket_key"), table_name="files")
    op.drop_table("files")
    # ### end Alembic commands ###
