name: Backend static analysis

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "backend/**"

jobs:
  run_linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
        
      - name: Install Poetry
        uses: Gr1N/setup-poetry@v7
      
      - name: Install dependencies
        working-directory: ./backend
        run: poetry install

      - name: Run Black
        working-directory: ./backend
        run: poetry run black --check src tests migration

      - name: Run Isort
        working-directory: ./backend
        run: poetry run isort --check src tests migration

      - name: Run Flake8
        working-directory: ./backend
        run: poetry run flake8 src tests migration
