name: Application Check

on:
  push:
    branches:
      - main
      - develop

jobs:
  run_linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
        
      - name: Install Poetry
        uses: Gr1N/setup-poetry@v7
      
      - name: Install dependencies
        run: poetry install

      - name: Run Black
        run: poetry run black --check src tests migration

      - name: Run Isort
        run: poetry run isort --check src tests migration

      - name: Run Flake8
        run: poetry run flake8 src tests migration

      - name: Run AutoFlake8
        run: poetry run autoflake8 --remove-unused-variables --recursive --exclude=__init__.py src tests migration
