name: Application Tests

on:
  push:
    branches:
      - main
      - develop

jobs:
  run_tests:
    runs-on: ubuntu-latest
    environment: testing

    env:
      ENVIRONMENT: test
      SQLALCHEMY_DB_URI: postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@${{ secrets.POSTGRES_HOST }}:${{secrets.POSTGRES_PORT}}/${{ secrets.POSTGRES_DATABASE }}
      APPLICATION_NAME: test-store
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      FIRST_SUPERUSER_NAME: ${{ secrets.FIRST_SUPERUSER_NAME }}
      FIRST_SUPERUSER_EMAIL: ${{ secrets.FIRST_SUPERUSER_EMAIL }}
      FIRST_SUPERUSER_PASSWORD: ${{ secrets.FIRST_SUPERUSER_PASSWORD }}
      CACHE_HOST: ${{ secrets.CACHE_HOST }}
      STORAGE_URL: ${{ secrets.STORAGE_URL }}
      STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
      EVENTS_BROKER_URL: ${{ secrets.EVENTS_BROKER_URL }}
      VERSION: 0.0.0

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DATABASE }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v7

      - name: Install dependencies
        run: poetry install

      - name: Run migrations
        run: make upgrade

      - name: Run Tests
        run: poetry run pytest
        env:
          ENVIRONMENT: test
